basePath: /
definitions:
  handlers.UserResponse:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sandbox project for REST API written in golang.
  termsOfService: http://swagger.io/terms/
  title: REST API with gorm
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: 1件取得
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.UserResponse'
      summary: ユーザ取得 GET:/users
swagger: "2.0"
