basePath: /
definitions:
  handlers.UserByNameResponse:
    properties:
      counts:
        type: integer
      users:
        $ref: '#/definitions/handlers.UserResponse'
    type: object
  handlers.UserResponse:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sandbox project for REST API written in golang.
  termsOfService: http://swagger.io/terms/
  title: REST API with gorm
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: 1件取得
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.UserResponse'
      summary: ユーザ取得 GET:/users
  /users/findname:
    get:
      consumes:
      - application/json
      description: 指定した名前に一致するユーザ一覧を取得
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.UserByNameResponse'
      summary: GET:/users/findname 指定した名前に一致するユーザ一覧を取得
swagger: "2.0"
